---
- name: Collect sshfp for dns records
  include_tasks: sshfp_records.yml
  with_items: "{{ groups['all'] }}"
  when: dns_facts_generate_sshfp

- name: Create temporary hostvars file
  tempfile:
    suffix: json
  register: tempfile
  changed_when: false

- name: Write hostvars to temporary file
  copy:
    content: "{{ hostvars }}"
    dest: "{{ tempfile.path }}"
  changed_when: false

- name: Generate facts
  script: "scripts/facts.py {{ ansible_hostname }} {{ tempfile.path }}"
  register: out
  changed_when: false

- name: Apply facts
  set_fact:
    pdns_auth_api_zones: "{{ out.stdout | from_json }}"
