---
- name: Create sshfp folder
  file:
    path: "{{ dns_facts_sshfp_path }}"
    state: directory
    owner: root
    mode: 0755

- name: Stat sshfp files
  find:
    paths: "{{ dns_facts_sshfp_path }}"
  register: sshfp_files

- name: Collect sshfp records
  command:
    ssh-keygen -r "{{ hostname }}"
  delegate_to: "{{ hostname }}"
  changed_when: false
  loop: "{{ hostvars.keys() | difference(sshfp_files.files | map(attribute='path') | map('basename') ) }}"
  loop_control:
    loop_var: hostname
  register: records
  ignore_unreachable: true

- name: Write sshfp records
  copy:
    dest: "{{ dns_facts_sshfp_path }}/{{ result.hostname }}"
    content: "{{ result.stdout }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ records.results | selectattr('unreachable', 'undefined') }}"
  loop_control:
    loop_var: result
